### ISSUE TITLE
NoSuchMethodError: 'java.lang.String gears.GearsBuilder.getUpgradeData()'|	at com.redislabs.WriteBehind.main(WriteBehind.java:93)|

### ISSUE THREAD

**Issue by psilberk** [RedisGears/rghibernate#99]
Running the provided example in the readme, using redisfab/redisgearsjvm:edge and latest version of rghibernate creates an error that makes me suspect that the gears.GearsBuiilder class in the image is in a different version than rghibernate jar:

docker run -d --name my-redis-container -p 6379:6379 redisfab/redisgearsjvm:edge

git clone git@github.com:RedisGears/rghibernate.git
cd rghibernate
git submodule update --init --recursive
make build
// creates artifacts/release/rghibernate-master-jar-with-dependencies.jar
redis-cli -x RG.JEXECUTE com.redislabs.WriteBehind < ./artifacts/release/rghibernate-master-jar-with-dependencies.jar

(error) java.lang.NoSuchMethodError: 'java.lang.String gears.GearsBuilder.getUpgradeData()'|	at com.redislabs.WriteBehind.main(WriteBehind.java:93)|

And in the docker image log: 
1:M 20 Dec 2022 22:39:34.952 * <module> JAVA_GEARS: RGHibernate 1.1.0

**Comment by jeswils-ap** [comment]
@psilberk Did you find a solution to this issue? Facing the same when trying to load this jar.

**Comment by psilberk** [comment]
Hi @jeswils-ap I don't remember how I got there, but looking at my notes I see that using another image:
docker run -d --name my-redis-container -p 6379:6379 redislabs/redisgears
Worked!
Please let me know if it works for you as well, good luck!
